"""
predict.py
Phase 2B: Scikit-Learn Random Forest / Gradient Boosting regression pipeline
for bin fill percentage prediction.

Trains on synthetic time-series generated by simulate.py, then provides
an inference function predict_stop_fills(date) that returns predicted
fill percentages for all stops on any given future date.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np

BASE_DIR = Path(__file__).resolve().parent.parent.parent
TRAINING_DATA_PATH = BASE_DIR / "data" / "processed" / "training_data.json"
STOPS_PATH = BASE_DIR / "data" / "processed" / "stops.json"
MODEL_PATH = BASE_DIR / "data" / "outputs" / "fill_model.joblib"
METRICS_PATH = BASE_DIR / "data" / "outputs" / "model_metrics.json"

FEATURE_COLUMNS = [
    "days_since_last_pickup",
    "day_of_week",
    "is_weekend",
    "is_festival",
    "is_market_day",
    "commercial_flag",
    "baseline_fill_rate",
    "event_multiplier",
]
TARGET_COLUMN = "fill_pct"

# ---------------------------------------------------------------------------
# Deterministic rule-based fallback (used when sklearn model unavailable)
# ---------------------------------------------------------------------------


def deterministic_fill_estimate(
    days_since_last: int,
    baseline_rate: float,
    is_commercial: bool,
    event_multiplier: float,
) -> float:
    """
    Rule-based fallback formula when no trained model is available.
    fill = clamp(0, 100, days * base_rate * commercial_mult * event_mult)
    """
    commercial_mult = 1.5 if is_commercial else 1.0
    fill = days_since_last * baseline_rate * commercial_mult * event_multiplier / 100.0 * 100
    return max(0.0, min(100.0, round(fill, 1)))


# ---------------------------------------------------------------------------
# Model training
# ---------------------------------------------------------------------------


def train_model():
    """
    Train a RandomForestRegressor on the simulated training data.
    Saves the model to data/outputs/fill_model.joblib and prints metrics.
    """
    try:
        import joblib
        from sklearn.ensemble import RandomForestRegressor
        from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
        from sklearn.model_selection import train_test_split
    except ImportError:
        print("[ERROR] scikit-learn is not installed. Run: pip install scikit-learn")
        print("[FALLBACK] Using deterministic rule-based fill estimator instead.")
        return None

    # Load training data
    with open(TRAINING_DATA_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    print(f"[INFO] Loaded {len(data)} training samples from {TRAINING_DATA_PATH}")

    # Build numpy arrays
    X = np.array([[row[col] for col in FEATURE_COLUMNS] for row in data], dtype=np.float64)
    y = np.array([row[TARGET_COLUMN] for row in data], dtype=np.float64)

    # Train/test split (80/20)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    print(f"[INFO] Training set: {len(X_train)} samples, Test set: {len(X_test)} samples")

    # Train Random Forest
    rf_model = RandomForestRegressor(
        n_estimators=120,
        max_depth=10,
        min_samples_split=4,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1,
    )
    rf_model.fit(X_train, y_train)

    # Evaluate
    y_pred_train = rf_model.predict(X_train)
    y_pred_test = rf_model.predict(X_test)

    train_r2 = r2_score(y_train, y_pred_train)
    test_r2 = r2_score(y_test, y_pred_test)
    test_rmse = mean_squared_error(y_test, y_pred_test) ** 0.5
    test_mae = mean_absolute_error(y_test, y_pred_test)

    print(f"[METRICS] Train R2:  {train_r2:.4f}")
    print(f"[METRICS] Test R2:   {test_r2:.4f}")
    print(f"[METRICS] Test RMSE: {test_rmse:.2f}%")
    print(f"[METRICS] Test MAE:  {test_mae:.2f}%")

    # Feature importance
    importances = dict(zip(FEATURE_COLUMNS, rf_model.feature_importances_))
    sorted_imp = sorted(importances.items(), key=lambda x: x[1], reverse=True)
    print("[INFO] Feature Importance Ranking:")
    for fname, imp in sorted_imp:
        bar = "#" * int(imp * 50)
        print(f"  {fname:30s} {imp:.4f}  {bar}")

    # Save model
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(rf_model, MODEL_PATH)
    print(f"[SUCCESS] Model saved to {MODEL_PATH}")

    # Save metrics
    metrics = {
        "algorithm": "RandomForestRegressor",
        "n_estimators": 120,
        "max_depth": 10,
        "train_samples": len(X_train),
        "test_samples": len(X_test),
        "train_r2": round(train_r2, 4),
        "test_r2": round(test_r2, 4),
        "test_rmse": round(test_rmse, 2),
        "test_mae": round(test_mae, 2),
        "feature_importances": {k: round(v, 4) for k, v in sorted_imp},
    }
    with open(METRICS_PATH, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)
    print(f"[SUCCESS] Metrics saved to {METRICS_PATH}")

    return rf_model


# ---------------------------------------------------------------------------
# Inference: predict fill levels for all stops on a given date
# ---------------------------------------------------------------------------


def load_model():
    """Load the trained model from disk; return None if unavailable."""
    try:
        import joblib
        if MODEL_PATH.exists():
            return joblib.load(MODEL_PATH)
    except (ImportError, OSError, ValueError):
        pass
    return None


def predict_stop_fills(
    date_str: str,
    stops: Optional[list] = None,
    model=None,
) -> list:
    """
    Predict fill percentages for all non-depot stops on a given date.

    Args:
        date_str: "YYYY-MM-DD" format date
        stops: List of stop dicts (loaded from stops.json if None)
        model: Trained sklearn model (loaded from disk if None)

    Returns:
        List of dicts with stop_id, zone_id, predicted_fill_pct, urgency, etc.
    """
    import sys
    # Allow import whether run as module or standalone script
    if __package__:
        from .simulate import get_event_multiplier
    else:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from simulate import get_event_multiplier

    if stops is None:
        with open(STOPS_PATH, "r", encoding="utf-8") as f:
            stops = json.load(f)

    date = datetime.strptime(date_str, "%Y-%m-%d")
    weekday = date.weekday()
    event_mult, event_name = get_event_multiplier(date)
    is_weekend = 1 if weekday in (5, 6) else 0
    is_festival = 1 if (event_name and event_name not in ("Weekend", "Weekly Subzi Mandi")) else 0
    is_market_day = 1 if event_name == "Weekly Subzi Mandi" else 0

    # Try loading model
    if model is None:
        model = load_model()
    use_ml = model is not None

    results = []
    for stop in stops:
        if stop.get("is_depot"):
            continue

        sid = stop["stop_id"]
        zid = stop["zone_id"]
        idx = int(zid.split("W")[1]) - 1
        sched_day_int = idx % 6
        baseline_rate = stop.get("baseline_fill_rate", 18.0)
        is_commercial = stop.get("commercial_flag", False)

        # Compute days since last pickup (simple: how many days since last scheduled day)
        day_diff = (weekday - sched_day_int) % 7
        days_since = day_diff if day_diff > 0 else 7

        if use_ml:
            feature_vec = np.array([[
                days_since,
                weekday,
                is_weekend,
                is_festival,
                is_market_day,
                1 if is_commercial else 0,
                baseline_rate,
                event_mult,
            ]], dtype=np.float64)
            pred = float(model.predict(feature_vec)[0])
        else:
            pred = deterministic_fill_estimate(
                days_since, baseline_rate, is_commercial, event_mult
            )

        pred = max(0.0, min(100.0, round(pred, 1)))

        # Classify urgency
        if pred >= 85.0:
            urgency = "CRITICAL"
        elif pred >= 65.0:
            urgency = "HIGH"
        elif pred >= 45.0:
            urgency = "MODERATE"
        else:
            urgency = "LOW"

        results.append({
            "stop_id": sid,
            "zone_id": zid,
            "ward_name": stop.get("ward_name", ""),
            "name": stop.get("name", ""),
            "lat": stop["lat"],
            "lon": stop["lon"],
            "predicted_fill_pct": pred,
            "urgency": urgency,
            "is_overflow_risk": pred >= 80.0,
            "event_flag": event_name is not None,
            "event_name": event_name,
            "days_since_last_pickup": days_since,
            "bin_capacity_kg": stop.get("bin_capacity_kg", 400),
        })

    return results


if __name__ == "__main__":
    # Step 1: Train model
    print("=" * 70)
    print("  PHASE 2B: TRAINING FILL PREDICTION MODEL")
    print("=" * 70)
    trained_model = train_model()

    # Step 2: Run sample inference
    if trained_model is not None:
        print()
        print("=" * 70)
        print("  SAMPLE INFERENCE: Predicting fills for 2026-08-20 (Thursday)")
        print("=" * 70)
        predictions = predict_stop_fills("2026-08-20", model=trained_model)
        fills = [p["predicted_fill_pct"] for p in predictions]
        print(f"[INFO] Predicted fills for {len(predictions)} stops")
        print(f"[STATS] Min: {min(fills):.1f}%, Max: {max(fills):.1f}%, Mean: {sum(fills)/len(fills):.1f}%")
        critical = [p for p in predictions if p["urgency"] == "CRITICAL"]
        high = [p for p in predictions if p["urgency"] == "HIGH"]
        print(f"[DISPATCH] CRITICAL stops (>=85%%): {len(critical)}")
        print(f"[DISPATCH] HIGH stops (>=65%%):     {len(high)}")

        # Save sample predictions
        pred_path = BASE_DIR / "data" / "outputs" / "sample_predictions.json"
        with open(pred_path, "w", encoding="utf-8") as f:
            json.dump(predictions, f, indent=2)
        print(f"[SUCCESS] Sample predictions saved to {pred_path}")
